version: '3'

services:

       tables:
              build: tables/
              volumes:
              - ./tables/:/app
              depends_on:
              - postgresdb

       postgresdb:
              image: postgres
              ports:
              - "5555:5432"
              environment:
              - POSTGRES_USER=postgres
              - POSTGRES_PASSWORD=pwd
              - POSTGRES_DB=company
       
       queries:
              build: queries/
              volumes:
              - ./queries/:/app
              depends_on:
              - postgresdb
       
       metabase:
              image: metabase/metabase
              ports:
              - "3000:3000"  # Access Metabase at http://localhost:3000
              depends_on:
              - postgresdb
       