version: '3'

services:

       tables:
              build: tables/
              volumes:
              - ./tables/:/app
              depends_on:
              - postgresdb
              environment:
              - POSTGRES_USER=${POSTGRES_USER}
              - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
              - POSTGRES_DB=${POSTGRES_DB}

       postgresdb:
              image: postgres
              ports:
              - "5555:5432"
              environment:
              - POSTGRES_USER=${POSTGRES_USER}
              - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
              - POSTGRES_DB=${POSTGRES_DB}
              #- POSTGRES_HOST=postgresdb
              volumes:
              - pgdata:/var/lib/postgresql/data
       
       queries:
              build: queries/
              volumes:
              - ./queries/:/app
              depends_on:
              - postgresdb
              environment:
              - POSTGRES_USER=${POSTGRES_USER}
              - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
              - POSTGRES_DB=${POSTGRES_DB}

       metabase:
              image: metabase/metabase
              ports:
              - "3000:3000"  # Access Metabase at http://localhost:3000
              volumes:
              - metabase-data:/metabase.db
              depends_on:
              - postgresdb

volumes:
       pgdata:
       metabase-data:
       